package com.byteowls.vaadin.chartjs.options.scale;

import com.byteowls.vaadin.chartjs.options.line.ScalesOptions;

/**
 * @author michael@team-conductor.com
 */
public class LogarithmicScale extends BaseScale<ScalesOptions, LogarithmicScale> {

    private LogarithmicTicks<LogarithmicScale> logarithmicTicks;

    public LogarithmicScale(ScalesOptions parent) {
        super(parent);
        type("logarithmic");
    }

    /**
     * It defines options for the tick marks that are generated by the axis.
     */
    @Override
    public LogarithmicTicks<LogarithmicScale> ticks() {
        if (this.logarithmicTicks == null) {
            this.logarithmicTicks = new LogarithmicTicks<>(getThis());
        }
        return this.logarithmicTicks;
    }

    @Override
    public LogarithmicScale getThis() {
        return this;
    }
}
