package com.byteowls.vaadin.chartjs.options.scale;

/**
 * The logarithmic scale is use to chart numerical data. It can be placed on either the x or y axis.
 * As the name suggests, logarithmic interpolation is used to determine where a value lies on the axis.
 *
 * @author michael@team-conductor.com
 */
public class LogarithmicScale extends BaseScale<LogarithmicScale> {

    private LogarithmicTicks<LogarithmicScale> logarithmicTicks;

    public LogarithmicScale() {
        type("logarithmic");
    }

    /**
     * It defines options for the tick marks that are generated by the axis.
     */
    @Override
    public LogarithmicTicks<LogarithmicScale> ticks() {
        if (this.logarithmicTicks == null) {
            this.logarithmicTicks = new LogarithmicTicks<>(getThis());
        }
        return this.logarithmicTicks;
    }

    @Override
    public LogarithmicScale getThis() {
        return this;
    }
}
